# Generated by Django 4.2 on 2025-05-22 09:30

import django.core.validators
from django.db import migrations, models
import habits.validators


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(max_length=250, verbose_name="Действие"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.PositiveIntegerField(
                validators=[habits.validators.validate_execution_time],
                verbose_name="Время на выполнение (в секундах)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                    habits.validators.validate_periodicity,
                ],
                verbose_name="Периодичность (в днях)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(max_length=150, verbose_name="Место"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Вознаграждение"
            ),
        ),
    ]
