name: CI/CD Pipeline

on:
  push:
    branches:
      - develop  # Запускаем при push в ветку develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          echo "::add-path::$(python -m site --user-base)/bin"

      - name: Install dependencies
        run: poetry install

      - name: Run linting
        run: |
          flake8 . --exclude=migrations

      - name: Run tests
        run: |
          pytest habits/tests.py users/tests.py telegram_bot/tests.py

      - name: Build Docker images
        run: docker-compose build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'  # Деплоим только из ветки develop

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh your_user@your_server_ip "
            cd /path/to/your/project
            git pull origin develop
            docker-compose up -d --build
            docker system prune -f --volumes
          "